---
name: Feature Request
description: Suggest a new feature
body:
    - type: textarea
      attributes:
          label: Feature Description
          description: What feature would you like?
          placeholder: Describe the feature you'd like to see
      validations:
          required: true
    - type: textarea
      attributes:
          label: Use Case
          description: Why do you need this feature?
          placeholder: Explain how this would help you
      validations:
          required: true
    - type: textarea
      attributes:
          label: Possible Implementation
          description: Any ideas on how to implement this?
          placeholder: Optional - any thoughts on implementation
